language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t kolsone/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true kolsone/react-test npm run test
after_success:
  - docker build -t kolsone/multi-client ./client
  - docker build -t kolsone/multi-nginx ./nginx
  - docker build -t kolsone/multi-server ./server
  - docker build -t kolsone/multi-worker ./worker

#log in to docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take those images and push them to docker hub
- docker push kolsone/multi-client
- docker push kolsone/multi-nginx
- docker push kolsone/multi-server
- docker push kolsone/multi-worker
